WIP: Feature/wrapper component
mubanjs/muban pull request #101
Opened 2023-05-16 13:55 UTC by jspolancor

Creates utilities for recursive parent lookup and tests
Create tests for the wrapper component in refDefinitions

2023-05-16 14:15 UTC, ThaNarie requested changes

2023-05-16 14:15 UTC, ThaNarie commented on src/lib/utils/domUtils.ts
> +export function recursiveParentComponentLookup(element: Element): Element | null {
I don't think the `recursive` should be in the function name, that's more of an implementation detail :)

Maybe rename this to `getOwnerComponent` ?

2023-05-16 14:15 UTC, ThaNarie commented on src/lib/utils/domUtils.test.ts
> +    expect(parent?.getAttribute('data-component')).toBe('my-component');
Better to use `https://github.com/testing-library/jest-dom#tohaveattribute`

2023-05-16 14:15 UTC, ThaNarie commented on src/lib/utils/domUtils.test.ts
> +describe('recursiveParentComponentLookup', () => {
It's missing the test for refs that belong to a wrapper.

Example HTML that can be used is in the original ticket:

```html
<div data-component="my-component">
  <div data-component="some-wrapper">
    <button data-ref="toggle">Toggle Content</button>
    <div data-ref="toggle-content" data-wrapper-boundary>
      <span data-ref="foo">label</span>
    </div>
  </div>
</div>
```

Here `data-ref="toggle"` should belong to `some-wrapper`, and not to `my-component` (which I think it currently incorrectly does).

2023-05-16 15:00 UTC, jspolancor commented on src/lib/utils/domUtils.ts
> +export function recursiveParentComponentLookup(element: Element): Element | null {
Makes sense, fixed!

2023-05-16 15:00 UTC, jspolancor commented on src/lib/utils/domUtils.test.ts
> +describe('recursiveParentComponentLookup', () => {
Done

2023-06-08 15:08 UTC, jspolancor commented on src/lib/utils/domUtils.test.ts
> +    expect(parent?.getAttribute('data-component')).toBe('my-component');
Fixed!

2023-06-12 07:56 UTC, ThaNarie approved these changes

2023-06-12 07:56 UTC, merged