Improve control over bindTemplate rendering
mubanjs/muban pull request #31
Opened 2021-11-20 14:18 UTC by ThaNarie

* autodetect initial rendering
* change immediateRender as a required config, to an override from the default
* combine the data and template function to be more integrated
* update docs
* add additional stories

fixes #26, #30

2021-11-22 11:08 UTC, psimk requested changes

2021-11-22 11:08 UTC, psimk commented on src/lib/bindings/applyBindings.ts
> +            // pass along ohw the result of the update function is going to be used,
```suggestion
            // pass along how the result of the update function is going to be used,
```

2021-11-22 11:08 UTC, psimk commented on src/lib/bindings/applyBindings.ts
> +              ref.element.innerHTML = result ? [].concat(result as any).join('') : '';
`result` can be `string | Array<string> | undefined`, right? So we only care to apply `[].concat` if `result` is an array:
```suggestion
              ref.element.innerHTML = Array.isArray(result) ? [].concat(result).join('') : result ?? '';
```

2021-11-22 11:24 UTC, ThaNarie commented on src/lib/bindings/applyBindings.ts
> +              ref.element.innerHTML = result ? [].concat(result as any).join('') : '';
The `concat` is a way to convert arrays and non-arrays to arrays, so you can join them whichever option is passed (TS just doesn't understand this).

If you do the `isArray` check, you don't need the `concat`, you can directly do the `join`.

2021-11-26 12:05 UTC, psimk commented on src/lib/bindings/applyBindings.ts
> +              ref.element.innerHTML = result ? [].concat(result as any).join('') : '';
So we can just omit `concat` then
```suggestion
              ref.element.innerHTML =  Array.isArray(result) ? result.join('') : result ?? '';
```

2021-11-26 12:07 UTC, psimk approved these changes

2021-11-26 12:20 UTC, ThijsTyZ approved these changes

2021-11-26 12:22 UTC, merged