Fix attr source conversion
mubanjs/muban pull request #35
Opened 2021-11-22 12:14 UTC by ThaNarie

Also add stories to test extraction in different input fields

2021-11-25 17:15 UTC, ThijsTyZ requested changes

2021-11-25 17:15 UTC, ThijsTyZ commented on src/lib/props/property-sources/createAttributePropertySource.ts
>            console.warn();
It looks a bit confusing that `value` is first not really the value but the source. Can we rewrite this to make it more clear?
```
        const source =
        propInfo.type !== Function
          ? propInfo.source.target!.getAttribute(propInfo.source.name) ?? undefined
          : undefined;

      if (source !== undefined) {
        return convertSourceValue(propInfo, value);
      } else {
        if (propInfo.type === Boolean) {
          console.warn();
        }
      }
      return undefined;
```

2021-11-25 17:15 UTC, ThijsTyZ commented on src/lib/props/property-sources/createAttributePropertySource.ts
>            console.warn();
What is the purpose of this empty `console.warn();`?

2021-11-26 11:58 UTC, ThaNarie commented on src/lib/props/property-sources/createAttributePropertySource.ts
>            console.warn();
I added TODO in code.
There should be a warning in that place, but needs some refinement first (is a separate note on the project board)

2021-11-26 11:59 UTC, merged