Improve error reporting for invalid refs
mubanjs/muban pull request #37
Opened 2021-11-22 12:42 UTC by ThaNarie

Output a proper warning that should educate the user what they are doing wrong.

fixes #36

2021-11-22 13:11 UTC, psimk approved these changes

2021-11-25 17:09 UTC, ThijsTyZ requested changes

2021-11-25 17:09 UTC, ThijsTyZ commented on src/lib/refs/refDefinitions.ts
> +        } catch (e) {
could you change `e` to `error` to be more explicit?

2021-11-25 17:09 UTC, ThijsTyZ commented on src/lib/refs/refDefinitions.ts
> +          element = (parent.querySelector<T>(`[data-ref="${this.ref}"]`) ?? null) as T | null;
How does this work? Usually `querySelector` doesn't throw an error if you try to select something that does not exist.

2021-11-26 09:13 UTC, psimk commented on src/lib/refs/refDefinitions.ts
> +          element = (parent.querySelector<T>(`[data-ref="${this.ref}"]`) ?? null) as T | null;
The `try / catch` isn't to capture errors for elements that don't exist, but to capture errors for invalid queries.
See the related issue https://github.com/mubanjs/muban/issues/36, you can also try it in the browser console:
```js
document.querySelector('[data-ref="input[type="radio"]:checked"]')
```

2021-11-26 11:52 UTC, ThijsTyZ commented on src/lib/refs/refDefinitions.ts
> +          element = (parent.querySelector<T>(`[data-ref="${this.ref}"]`) ?? null) as T | null;
Got it. Thanks for the explanation

2021-11-26 11:52 UTC, ThijsTyZ approved these changes

2021-11-26 11:59 UTC, merged