Improve bindMap and other bindings after bindTemplate updates
mubanjs/muban pull request #38
Opened 2021-11-24 10:39 UTC by ThaNarie

Previously there were some memory leaks regarding bindMap when
the HTML was updated with bindTemplate. New bindings were created
to make everything work, but old bindings were not removed.

The fix here is done in two ways:

1) The `getRefs` for collections how returns an array or refs that
are managed by the collection itself, so when the collection changes,
these refs can be set to `undefined`, so any bindings to this ref
will be cleaned up.

2) Additionally, bindMap now cleans up its own bindings, and registers
it watcher to the Component instance, so both gets cleaned up.

2021-11-25 16:51 UTC, ThijsTyZ commented on src/lib/bindings/applyBindings.ts
> +          () => unref(binding.ref).map((ref) => unref(ref)),
Why not:
```suggestion
          () => unref(binding.ref).map(unref),
```
?

2021-11-25 16:52 UTC, ThijsTyZ commented on src/lib/bindings/applyBindings.ts
> +            const reff = unref(binding.ref).map((r) => unref(r));
why not:
```suggestion
            const reff = unref(binding.ref).map(unref);
```
?

2021-11-25 16:52 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +  getElements(): Array<RefElementType>;
```suggestion
  getElements(): ReadonlyArray<RefElementType>;
```

2021-11-25 16:54 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +          removeBindingList.forEach((binding) => binding && binding());
Would this be possible?
```suggestion
          removeBindingList.forEach((binding) => binding?.());
```

2021-11-25 16:54 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +  getElements(): Array<RefElementType>;
```suggestion
  getElements(): ReadonlyArray<RefElementType>;
```

2021-11-25 16:55 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +      return ref.value.map((r) => unref(r));
```suggestion
      return ref.value.map(unref);
```

2021-11-25 16:56 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +  ref: Ref<Array<Ref<T>>>,
Maybe we should change this to `ReadonlyArray` too?

2021-11-25 16:56 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +  ref: Ref<Array<Ref<T>>>;
Maybe we should change this to `ReadonlyArray` too?

2021-11-25 16:56 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +  ref: Ref<Array<Ref<T>>>;
```suggestion
  ref: Ref<ReadonlyArray<Ref<T>>>;
```

2021-11-25 16:56 UTC, ThijsTyZ commented on src/lib/bindings/bindingDefinitions.ts
> +  ref: Ref<Array<Ref<T>>>,
```suggestion
  ref: Ref<ReadonlyArray<Ref<T>>>,
```

2021-11-25 16:57 UTC, ThijsTyZ commented on src/lib/refs/refDefinitions.ts
> +      const elementsRef = ref([]) as Ref<Array<Ref<T>>>;
```suggestion
      const elementsRef = ref([]) as Ref<ReadonlyArray<Ref<T>>>;
```

2021-11-25 16:59 UTC, ThijsTyZ commented on src/lib/refs/refDefinitions.ts
> +        return elements.map((e) => ref(e) as Ref<T>);
```suggestion
        return elements.map<Ref<T>>(ref);
```

2021-11-25 17:00 UTC, ThijsTyZ commented on src/lib/refs/refDefinitions.ts
> +          return elementsRef.value.map((ref) => unref(ref));
```suggestion
          return elementsRef.value.map(unref);
```

2021-11-25 17:00 UTC, ThijsTyZ commented on src/lib/refs/refDefinitions.ts
> +          return instancesRef.value.map((ref) => unref(ref));
```suggestion
          return instancesRef.value.map(unref);
```

2021-11-25 17:02 UTC, ThijsTyZ requested changes
Please see suggestions in the PR

2021-11-26 09:17 UTC, psimk commented on src/lib/bindings/bindingDefinitions.ts
> +      return ref.value.map((r) => unref(r));
@ThijsTyZ while your suggestion might work now, if `unref` is ever updated to accept more than 1 argument, then this will break. In general, we should discourage straight up passing of functions and we encourage to always wrap them in callbacks to be safe against any parameter additions/changes.

2021-11-26 09:18 UTC, psimk commented on src/lib/refs/refDefinitions.ts
> +        return elements.map((e) => ref(e) as Ref<T>);
See my comment https://github.com/mubanjs/muban/pull/38#discussion_r757340863

2021-11-26 09:18 UTC, psimk commented on src/lib/refs/refDefinitions.ts
> +          return elementsRef.value.map((ref) => unref(ref));
See my comment https://github.com/mubanjs/muban/pull/38#discussion_r757340863

2021-11-26 09:18 UTC, psimk commented on src/lib/refs/refDefinitions.ts
> +          return instancesRef.value.map((ref) => unref(ref));
See my comment https://github.com/mubanjs/muban/pull/38#discussion_r757340863

2021-11-26 11:28 UTC, ThaNarie commented on src/lib/bindings/bindingDefinitions.ts
> +      return ref.value.map((r) => unref(r));
I agree, unless we're in control of both ends. In this case we know `.map` passes additional parameters, and we've seen issues with that in the past :)

2021-11-26 11:47 UTC, merged