WIP Feature/array of sources
mubanjs/muban pull request #55
Opened 2022-01-11 14:54 UTC by jspolancor

Adds the possibility to pass an array of source configurations for a prop

2022-01-11 22:45 UTC, ThaNarie requested changes

2022-01-11 22:45 UTC, ThaNarie commented on src/lib/props/getComponentProps.ts
> +  propInfo.forEach((propTypeInfo) => {
I would use a normal for loop, so you can early-exit once a source is valid.

2022-01-12 15:16 UTC, jspolancor commented on src/lib/props/getComponentProps.ts
> +  propInfo.forEach((propTypeInfo) => {
Done

2022-01-12 15:35 UTC, ThaNarie commented on src/lib/props/getComponentProps.ts
> +  propInfo.forEach((propTypeInfo) => {
The whole reason for the `for` loop is so this can do a `return` statement (if the `getValueFromSource` succeeds) :)
Now you're still assigning it to a let, and returning it after the complete loop has finished.

Also, should be better to use a `for/of` loop. :)

2022-01-12 15:38 UTC, psimk commented on src/lib/props/getComponentProps.ts
> +  propInfo.forEach((propTypeInfo) => {
I think @ThaNarie meant something along the lines of :arrow_down: 
```ts
for (const info of propInfo) {
  try {
    return getValueFromSource(info, sources);
  } catch {
    return undefined;
  }
}
```

if `getValueFromSource` throws, then `catch` will be triggered and we will return `undefined`.

2022-01-12 15:44 UTC, psimk commented on src/lib/props/getComponentProps.ts
> +): any {
whenever possible we should use `unknown` instead of `any`.

If we define a value as `any`, then TypeScript will just think:
> "ok, this can be anything so do what you want with it"

but if we define it as `unknown`, TypeScript will then think:
> "oh, neither you and me know what this is huh? then please before doing anything with this value, cast it to a valid type"

reference: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

2022-01-12 15:45 UTC, psimk commented on src/lib/props/getComponentProps.ts
>        let extractedValue;
I think this one is on @ThaNarie, but `extractadValue`'s type defaults to `any`, which is _unsafe_.
see my previous comment on this: https://github.com/mubanjs/muban/pull/55/files#r783199019

2022-01-12 16:32 UTC, jspolancor commented on src/lib/props/getComponentProps.ts
> +  propInfo.forEach((propTypeInfo) => {
ahhh got it!  I just changed the loop, but I didn't add the undefined return inside the catch as it will always return something and will not try with the next array item

2022-01-12 16:35 UTC, jspolancor commented on src/lib/props/getComponentProps.ts
>        let extractedValue;
I updated the variable to have an unknown type
```ts
let extractedValue: unknown;
```

2022-01-14 17:48 UTC, psimk approved these changes

2022-01-27 10:01 UTC, ThaNarie approved these changes

2022-01-27 10:22 UTC, merged