Only allow passing reactive values to component props in bindings
mubanjs/muban pull request #59
Opened 2022-01-19 18:28 UTC by jspolancor

Updates the RefOrValue type to allow only refs and not values, also adds a condition to allow functions not wrapped in refs

2022-01-19 18:34 UTC, ThaNarie requested changes

2022-01-19 18:34 UTC, ThaNarie commented on src/lib/refs/refDefinitions.types.ts
> +  [P in keyof T]: T[P] extends Function ? T[P] : Ref<T[P]>;
Recently we had a use cases where functions should also allowed to be passed as `ref`;

When function props are received from a parent and forwarded to a child, those props are initially undefined. So to make this work, you have to wrap them in a `computed`, which means we should still allow a `Ref` there.

So with that:
- function: both Ref or a value
- anything else: only a Ref

2022-01-19 19:52 UTC, jspolancor commented on src/lib/refs/refDefinitions.types.ts
> +  [P in keyof T]: T[P] extends Function ? T[P] : Ref<T[P]>;
Done

2022-01-19 20:36 UTC, ThaNarie approved these changes

2022-01-20 20:49 UTC, psimk approved these changes

2022-01-27 09:57 UTC, merged