Checks if 'previousCssValue' exists
mubanjs/muban pull request #60
Opened 2022-01-19 19:32 UTC by gimenezpablonl

Before removing classes, check if 'previousCssValue' value is set. Fix #52

2022-01-19 19:40 UTC, ThaNarie requested changes
The code looks good, however:

* Could you change your commit message according to https://cbea.ms/git-commit/, and force push it in this same branch?
* This wasn't specifically mentioned in the ticket, but could you add a test story with the different ways the css binding can be used, so we can be sure we don't break this in the future? In `test-storybook/src/components/bindings`.

Thanks!

2022-01-20 20:06 UTC, ThaNarie requested changes
Would you be able to update the stories so the CSS binding is actually updated, let's say by conditionally adding 0, 1 or 2 classes (using both string and object methods)?

Currently it's static, so the "removing when changing" is not really tested.

To make the tests even more useful, you could add an an existing classname to the `box` element in the template, and see if it gets persisted.

2022-01-22 19:22 UTC, ThaNarie requested changes
Some suggestion to improve the way components are written, and how to add testing to them :)

2022-01-22 19:22 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +    <div data-ref="box" class="bg-primary">
With this suggestion:
> To make the tests even more useful, you could add an an existing classname to the box element in the template, and see if it gets persisted.

I meant an existing classname that is not controlled by the binding (one that should always stay there), like a `class=""leave-this-hear bg-primary"`.

Having an initial class that _is_ controlled by the binding there is also a good thing, so I would do both :)

2022-01-22 19:22 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +import type { Story } from '@muban/storybook/types-6-0';
For new stories I'd like to use the CFSv3 (object) format, so:

```ts
import type { Story } from '@muban/storybook';

export const CssObject: Story = {
  render() {
    return {
      component: ...
      template: ...
    }
  }
}
```

2022-01-22 19:22 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +/* eslint-disable max-lines */
This comment can be removed from this file

2022-01-22 19:22 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +/* eslint-disable max-lines */
This repo doesn't have pre-commit hooks set up, but could you at lease configure your editor to run eslint/prettier on save, so this files is properly formatted? :)

2022-01-22 19:22 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +/* eslint-disable max-lines */
To make this test even more useful, I think we should add "interaction testing" using the `play` function.

More info: https://storybook.js.org/docs/react/writing-tests/interaction-testing
Example: https://github.com/mubanjs/muban/blob/ede37994c1cd8716b27951873d0be91e36e1c1fc/test-storybook/src/components/core/provideInject/ProvideInject.stories.ts#L210-L254

With that, we can (using code), change the checkboxes, and check if the classes are actually correctly added :)

2022-01-26 20:45 UTC, gimenezpablonl commented
Last commit has a storybook related to #24. Can't reproduce that issue.

2022-01-26 22:35 UTC, ThaNarie requested changes
Nice progress, just a few more remarks, but we're close!

One general note (that you don't have to update here) but please do keep it in mind or any other Stories or Unit tests that you will be writing:

* Keep the Stories/Tests as simple as possible
* The current setup with the dynamic nature of `createCssStory`, `createCssComponent` and things like the dynamic fetching of the `classList` based on the `defaultValue`, could make it harder to follow what's going on
* Besides testing functionality, Stories/Tests are also meant as a "showcase / example" of how to use a certain feature. The simpler they look, the easier to follow.
* And lastly, the more complex your Story/Test, the harder it is to identify if – when they fail – the issue lies in the library code, or you Story/Test itself :D

It's a fine line to walk – reusing code can be fine, as long as it's easy to follow what's going on :)

2022-01-26 22:35 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +  await expect(screen.getByTestId('box').classList.value).toBe('box bg-primary');
If you use `jest-dom`, you can use specific matchers using less code :)
https://github.com/testing-library/jest-dom#tohaveclass

Just make sure to install and `import '@testing-library/jest-dom'` at the top of the file

2022-01-26 22:35 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +import type { Binding } from '../../../../../types/lib/bindings/bindings.types';
```suggestion
import type { Binding } from '@muban/muban/types/lib/bindings/bindings.types';
```

2022-01-26 22:35 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +} from '@muban/muban';
```suggestion
import type { ComponentFactory, ComponentRefItem } from '@muban/muban';
import { bind, defineComponent, computed, ref, refCollection } from '@muban/muban';
```

2022-01-26 22:35 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +    <input data-ref="checkbox" data-testid="checkbox-box" type="checkbox" value="box" disabled />
The purpose of the `box` class (`class="box bg-primary"`) was to _not_ have it included in the bindings, to see if they would leave it alone completely. But with the `refs.checkboxes.getElements()` code in the stories, the `box` class is part of the binding.

So I would suggest to remove this `<p>`, and update the `play` tests that had `foobar-0` attached to `box`.

2022-01-26 22:35 UTC, ThaNarie commented on src/lib/bindings/dom/cssBinding.ts
>        // then store and set our new classes
I observed an error in the console on the `target.classList.add(...classes.split(/\s/gi))` lines, when classes is an empty string (after removing the `box` input).

Doing `target.classList.add('')` throws a `DOMException`. I think that lines needs an `if`-statement as well :)

2022-01-28 18:11 UTC, jspolancor commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +  await expect(screen.getByTestId('box').classList.value).toBe('box bg-primary');
We tried to configure this but is quite tricky, the jest-dom import expects a globally defined **_expect_** variable to extend
![image](https://user-images.githubusercontent.com/5639960/151598969-17241b69-7230-44f1-af6b-526468b22603.png)
But in storybook we're supossed to use the imported **_expect_** from the storybook/jest package
```javascript
import { expect } from '@storybook/jest';
```
There must be a way to make it work, but I think this dependency shouldn't be a blocker for this PR, we can use the expect from @storybook/jest and try to make it work in a specific issue for jest-dom installation

2022-01-28 18:50 UTC, ThaNarie commented on test-storybook/src/components/bindings/css/Css.stories.ts
> +  await expect(screen.getByTestId('box').classList.value).toBe('box bg-primary');
I got this to work by doing:

In `test-storybook/.storybook/preview.js`, add this at the top:
```ts
import { expect } from '@storybook/jest';
import * as matchers from '@testing-library/jest-dom/matchers';
expect.extend(matchers);
```

And then in your story file, you only have to import:
```ts
import { expect } from '@storybook/jest';
```

2022-02-03 16:15 UTC, jspolancor approved these changes

2022-02-25 15:27 UTC, merged