Feature/lazy component simplification
mubanjs/muban pull request #61
Opened 2022-01-21 23:30 UTC by jspolancor

- Simplifies the lazy loading of components by removing the need for the _supportLazy()_ function or the _/* webpackExports: "lazy" */_ flag
- Updates docs to reflect this change
- Adds stories for this feature

2022-01-22 11:01 UTC, ThaNarie commented on docs/api/component.md
> +  componentName?: string,
I would probably call this `exportName`.

The `componentName` woud suggest `name: 'lazy-component',`.

2022-01-22 11:10 UTC, ThaNarie commented on docs/api/component.md
> +  getComponent: () => Promise<{ [key: string]: ComponentFactory }>,
I wonder if we can bind `[key: string]` to `componentName/exportName` when that 3rd parameter is passed, so we know for sure it's matching.

With things like template strings in types, we might even be able to convert the `displayName` like `lazy-component` to the `PascalCase` variant as a type; https://github.com/sindresorhus/type-fest#change-case

With that, we could generate a `type` helper that would:
- receive the values of the first and 3rd parameter
- if third is passed, return that directly
- otherwise, convert the first parameter to `PascalCase `
- use the return into value to be used instead of `[key: string]`

2022-01-22 11:13 UTC, ThaNarie commented on src/lib/api/apiLazy.ts
> +  const pascalDisplayName = displayName.split('-').map(capitalize).join('');
We already include the `change-case` library and use it in a few cases, so I'd rather use that here.

2022-01-22 11:16 UTC, ThaNarie commented on docs/api/component.md
> +    lazy('my-lazy-component', () => import('./MyLazyComponent'), 'LazyComponent')
This `my-lazy-component` doesn't match up with `name: 'lazy-component',` in the imported component, so it won't work.

I suggest to:
- use `'lazy-component'` as the display name (in both places)
- change the "file name" to `./LazyComponent`
- change the export to `MyLazyComponent`, since this feature/example purely focusses on changing the export to something else, that should be the main thing that's different in naming to stand out.

2022-01-22 11:20 UTC, ThaNarie commented on docs/api/component.md
> +  name: 'lazy-component',
This `lazy-component` doesn't match up with `lazy('my-lazy-component', ...` in the code below. It should be `name: 'my-lazy-component',`

To make this more clear, I would add 2 comments:
- at the top, add `// MyLazyComponent.ts` to clearly indicate the filename
- above `export const LazyComponent`, add
```
// Export here is `LazyComponent` instead of `MyLazyComponent` to not match convention,
// which can be explicitly provided in the example below
```

2022-01-22 11:21 UTC, ThaNarie commented on docs/api/component.md
> +    lazy('my-lazy-component', () => import('./MyLazyComponent'), 'LazyComponent')
I would probably like a basic example where we don't provide the 3rd parameter as well, since that would be used 99% of the time.

2022-01-22 11:22 UTC, ThaNarie commented on src/lib/api/apiLazy.ts
> +  getComponent: () => Promise<{ [key: string]: ComponentFactory }>,
I wonder if we can bind `[key: string]` to `componentName/exportName` when that 3rd parameter is passed, so we know for sure it's matching.

With things like template strings in types, we might even be able to convert the `displayName` like `lazy-component` to the `PascalCase` variant as a type; https://github.com/sindresorhus/type-fest#change-case

With that, we could generate a `type` helper that would:
- receive the values of the first and 3rd parameter
- if third is passed, return that directly
- otherwise, convert the first parameter to `PascalCase `
- use the return into value to be used instead of `[key: string]`

2022-01-22 11:23 UTC, ThaNarie commented on src/lib/api/apiLazy.ts
> +  componentName?: string,
I would probably call this `exportName`.

The `componentName` woud suggest `name: 'lazy-component',`.

2022-01-22 11:25 UTC, ThaNarie requested changes
Code looks mostly good, feedback is around types / docs / examples :)

2022-01-24 19:21 UTC, psimk requested changes
* `muban/demo/examples/src/other/dynamic/Dynamic.stories.ts` still seems to contain the `webpackExports: "lazy"`

2022-01-24 19:21 UTC, psimk commented on src/lib/api/apiLazy.ts
>  export function lazy(
It would be nice to place a `jsdoc` comment atop this function, adding descriptions to each of the parameters and explaining why we might need the `componentName/exportName`.

reference: https://jsdoc.app/howto-es2015-modules.html

2022-01-24 19:21 UTC, psimk commented on src/lib/api/apiLazy.ts
> +export const lazy = supportLazy(MyComponent);
I don't think this comment adds a lot of value, IMO it would be better to specify that this is deprecated using the `@deprecated` jsdoc helper tag.

@ThaNarie maybe we should also add a `console.warn` with the `component.displayName` if `NODE_ENV` is `development` ?

reference: https://jsdoc.app/tags-deprecated.html

2022-01-24 21:14 UTC, jspolancor commented on src/lib/api/apiLazy.ts
> +  const pascalDisplayName = displayName.split('-').map(capitalize).join('');
Done

2022-01-24 21:15 UTC, jspolancor commented on docs/api/component.md
> +  name: 'lazy-component',
Done

2022-01-24 21:15 UTC, jspolancor commented on docs/api/component.md
> +    lazy('my-lazy-component', () => import('./MyLazyComponent'), 'LazyComponent')
Done

2022-01-24 21:17 UTC, jspolancor commented on src/lib/api/apiLazy.ts
> +  getComponent: () => Promise<{ [key: string]: ComponentFactory }>,
Nice catch! I think with the change @ThaNarie is suggesting this will be fixed, @ThaNarie I have no idea how to do that, help me please!

2022-01-24 21:17 UTC, jspolancor commented on src/lib/api/apiLazy.ts
> +  componentName?: string,
Done

2022-01-24 21:32 UTC, ThaNarie commented on src/lib/api/apiLazy.ts
> +export const lazy = supportLazy(MyComponent);
> IMO it would be better to specify that this is deprecated using the @deprecated jsdoc helper tag.

I'd rather just error – it's already a breaking change anyway, and it's very easy to just remove these and clean up, you're already changing all usages of lazy code to this new setup anyway.

2022-01-24 21:39 UTC, ThaNarie commented on src/lib/api/apiLazy.ts
> +  getComponent: () => Promise<{ [key: string]: ComponentFactory }>,
@psimk your playground was not accurate (where promises were placed), but you are correct in general :)

```ts
function lazy(name: string, b: () => Promise<{[key: string]: 42 }>) {
    return {} as unknown;
}

lazy('my-component-name', () => new Promise(r => r(
{
    hello: 42
    anInnoccentExport: 96, // this indeed gives an error
}
)))
```

And indeed @jspolancor, if we get it to work, we should be good :)

2022-01-25 23:21 UTC, jspolancor commented on src/lib/api/apiLazy.ts
> +  getComponent: () => Promise<{ [key: string]: ComponentFactory }>,
This was solved by @ThaNarie in[ this commit](https://github.com/mubanjs/muban/pull/61/commits/57fcfeadf62f93cf2caa657e7554f7fb35b3c3cd) ✅

2022-01-25 23:21 UTC, jspolancor commented on src/lib/api/apiLazy.ts
>  export function lazy(
Done

2022-01-25 23:21 UTC, jspolancor commented on src/lib/api/apiLazy.ts
> +export const lazy = supportLazy(MyComponent);
I just added the deprecated tag, Done

2022-01-26 16:07 UTC, ThaNarie approved these changes

2022-01-26 16:25 UTC, psimk approved these changes

2022-01-27 11:31 UTC, merged