Updates refElement() and refComponent() querying
mubanjs/muban pull request #63
Opened 2022-02-04 20:39 UTC by jspolancor

- Replaces querySelector with querySelectorAll to select matching elements in the refElement and refComponent functions
- Adds new tests for the feature

2022-02-04 22:40 UTC, ThaNarie requested changes
Code and tests look good, just a few small things to improve :)

2022-02-04 22:40 UTC, ThaNarie commented on src/lib/refs/refDefinitions.ts
> +          ) as NodeListOf<T>;
You sure this cast is needed?

2022-02-04 22:40 UTC, ThaNarie commented on src/lib/refs/refDefinitions.ts
> +            ) || null;
Since we're already guarding with `ensureElementIsComponentChild`, there is need to do that again at the bottom, so we could already return here.

With that, it would be nicer to move the `ensureElementIsComponentChild` at the bottom in the `if` as well

2022-02-04 22:40 UTC, ThaNarie commented on src/lib/refs/refDefinitions.ts
> +          ) || null;
Same remark as above regarding returning with `ensureElementIsComponentChild`

2022-02-07 14:55 UTC, jspolancor commented on src/lib/refs/refDefinitions.ts
> +          ) as NodeListOf<T>;
not really 😬, fixed

2022-02-07 14:55 UTC, jspolancor commented on src/lib/refs/refDefinitions.ts
> +            ) || null;
Fixed

2022-02-07 15:00 UTC, jspolancor commented on src/lib/refs/refDefinitions.ts
> +          ) || null;
It's posible in the refElement function, but in the refComponent there's a condition in line 298 that needs the `element` variable to be set, if I add the return to the array.find than condition will never be checked

2022-02-25 13:12 UTC, ThaNarie approved these changes

2022-02-25 13:13 UTC, merged