Input specific propType source
mubanjs/muban pull request #75
Opened 2022-03-10 18:47 UTC by jspolancor

- Creates the createFormPropertySource() function and adds it to the global property sources
- Creates tests cases for createFormPropertySource()
- Creates stories for createFormPropertySource()

**Notes:** 
This is a WIP PR, there's a few things that I don't fully understand and need feedback about

1. I had to change the type `PropTypeInfo` and set `name` as optional, because for the form propType source it can be optional, without changing that it was imposible to create an unnamed source, this change forced me to update the other ...PropertySource() functions, adding a `!` at the end of `propInfo.source.name`, all tests are passing but I'm not 100% sure about this type change
2. As there are too many conditions and special cases, inside createFormPropertySource() I created one function for every major case, and then using the `flow` function from lodash I call them all one by one, `flow` is just a pipe
3. I haven't touched the docs yes, I know for sure many files need to be updated, but I don't have a full understanding of all the doc files yet, @ThaNarie could you please make me a list of all the files that need to be updated? that would be super useful!
4. Regarding `<input type="file"/>`, I added a function inside `createFormPropertySource()` to check for file inputs, but testing it I realized it's not very useful... because it is impossible to set the value of an input file directly, so initially when setting the prop the value will be undefined, so from the rendered HTML from a CMS we cannot get an initial value... It's working, but I don't fully understand how we could use it in an app, i will rather just bind a change event to the input

I think that's it, please let me know your thoughts

2022-03-14 16:16 UTC, ThaNarie requested changes
Not checked everything yet, but here are some initial comments :)

2022-03-14 16:20 UTC, ThaNarie commented
> I had to change the type `PropTypeInfo` and set `name` as optional ...

That's strange, I will need to look at that (commented the same)

> As there are too many conditions and special cases, inside createFormPropertySource() I created one function for every major case, and then using the flow function from lodash I call them all one by one, flow is just a pipe

That's fine, I added a comment on the usage of `pipe` itself though :)

> I haven't touched the docs yet, I know for sure many files need to be updated, but I don't have a full understanding of all the doc files yet, @ThaNarie could you please make me a list of all the files that need to be updated? that would be super useful!

I think just these two:

* https://mubanjs.github.io/muban/guide/props.html#source
* https://mubanjs.github.io/muban/api/props.html#source

> Regarding `<input type="file"/>` ...

Jep you're right, this doesn't make much sense. I would leave it out – and only add it back if someone finds a reason to use it :)

2022-03-23 14:56 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +        return flow([formDataValue, textInput, checkbox, nonBooleanCheckbox, multiSelect, file])();
Fixed!

2022-03-23 14:57 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +          target: form.querySelector('#description')! as HTMLElement,
Fixed!

2022-03-23 14:57 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +const form = document.createElement('form');
Makes total sense, fixed!

2022-03-24 11:16 UTC, ThaNarie requested changes

2022-03-24 11:16 UTC, ThaNarie commented on src/lib/props/propDefinitions.types.ts
> +    name?: string;
Okay, so the reason this was required here, and undefined further up, is because this type is never constructed directly, but always created by a util. This util copies over fallback values if the `name` is missing:

```ts
name: (sourceOption && 'name' in sourceOption && sourceOption.name) || propName,
```
in `getComponentProps.ts`

What I did in `src/lib/props/property-sources/createClassListPropertySource.test.ts` was to provide a fixed value there, so TS would shut up. Since in `createClassListPropertySource`, the `name` is an override for the `propName`.

However, for the `form` logic, it's not meant as a fallback, but rather a logic switch.

So we need to decide between:

1. Changing how `name` is passed along as "fallback" value
2. Changing how the `form` source is using the `name`, and using another field (like `fieldName`) for that specific purpose
3. Same as 2, but keep using `name` as is for fields, but adding an explicit option to get the complete form data (instead of currently omitting the `name`). Maybe just simply `formData: true`?

I think my preferences goes to 3️⃣. And then we can revert the `optional` change that you did.

2022-03-29 13:44 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +    it('Should return the checked value if the target is a checkbox and the propType is boolean', () => {
Done

2022-03-29 13:45 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +    it('Should return an array of strings if the target is checkbox and the propType is Array', () => {
Fixed, and yes, they are ignored completely

2022-03-29 13:45 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +        JSON.stringify(['apple', 'banana']),
Fixed

2022-03-29 13:45 UTC, jspolancor commented on test-storybook/src/components/core/props/FormProps.stories.ts
> +      formData: propType.object.source({ type: 'form', target: 'formRef' }),
Removed! I was going to convert all formData keys to values, but it could potentially give the wrong idea of how the formData extraction works to the readers of the story

2022-03-29 13:48 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +    it('Should return the checked value if the target is a checkbox and the propType is boolean', () => {
Done! I didn't add all 6 variations to all tests to avoid repetition, but grouped them properly instead

2022-04-18 21:51 UTC, jspolancor commented on src/lib/props/propDefinitions.types.ts
> +    name?: string;
Finally done! I added the `formData` boolean to `SourceOptionForm` and totally reverted the optional change I did

2022-04-19 09:46 UTC, ThaNarie commented on test-storybook/src/components/core/props/FormProps.stories.ts
> +  template: () => html`<div data-component="props">
A radio group usually consists of multiple radio inputs :D

2022-04-19 09:49 UTC, ThaNarie commented on test-storybook/src/components/core/props/FormProps.stories.ts
> +});
My idea was to (also) check the extracted json output, to see of those values are what we expecting.

2022-04-19 09:54 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
I think the check on `name` is not needed anymore? Similarly, the warning also doesn't have to mention it like that?

2022-04-19 09:58 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +      const validForm: PropTypeInfo = {
For the completeness, could we also have a test where:
* `name` is `email`
* `source.name` is `''`
* `source.target` is a form

I believe we don't have that version yet.

2022-04-19 10:01 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
Besides the warning, the code below doesn't do anything with `source.formData` yet.

It seems to implicitly do something with `return childInputValue.length ? value : formData;`, but since it's lacking comments, i'm unsure what the intention is there.

2022-04-19 10:03 UTC, ThaNarie commented on src/lib/props/propDefinitions.types.ts
> +    name?: string;
Did you also updated the examples / documentation to include this explicit `formData` boolean? :)

2022-04-20 22:14 UTC, jspolancor commented on test-storybook/src/components/core/props/FormProps.stories.ts
> +  template: () => html`<div data-component="props">
I added another one, however, getting the radio button value using a ref for every input does not make much sense, I think for radio buttons the best option is to use the `formData` property, what do you think? maybe an specific example for radio buttons in the docs would be helpful

2022-04-20 22:15 UTC, jspolancor commented on test-storybook/src/components/core/props/FormProps.stories.ts
> +});
😅 Done

2022-04-20 22:32 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
You're right, removed. What do you mean with the warning? it's logging `propInfo.name` and `propInfo.type.name`, not `propInfo.source.name`

2022-04-20 23:56 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
I just realized we do not need the formData boolean, It is needed only for jest files, we could just pass an empty string for 'name'  in the tests to make typescript happy, when actually setting the values with `propType.{type}.source` 'name' can be omitted. I just refactored the function, as the FormData will be used only when the target is a form element I added each possible condition inside the `formDataValue` function:

- The type is Object but a name was given: show an error and return undefined
- The type is Object but no name was given: return FormData
- The type is NOT Object and a name was given:
   - If the type is Array return FormData.getAll(), useful for multiple inputs with the same name like checkboxes
   - If the type is NOT Array return FormData.getAll()[0] converted with `convertSourceValue`
- Anything else: return undefined

All tests are passing and I think it's way more concise for devs, I like it a lot, what do you think?

2022-04-20 23:59 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +      const validForm: PropTypeInfo = {
I think we already have it, it's the same as `it('Should return FormData when using type "Object" and an unnamed source')`

2022-04-21 00:06 UTC, jspolancor commented on src/lib/props/propDefinitions.types.ts
> +    name?: string;
as I removed it completely I just added an example on how to extract values from the form ref FormData object

2022-04-25 14:50 UTC, ThaNarie commented on test-storybook/src/components/core/props/FormProps.stories.ts
> +  template: () => html`<div data-component="props">
No, i mean that just with a `select`, you want multiple options to select from, and test that the correct one is indeed extracted.

What you have added in the last commit, is adding a separate group with again a single option. (which is still useful, as it's a case where it's undefined, which wasn't tested yet there.

However, you are correct that using `formData` is probably the easiest approach from a user point of view.
Unless we support a `refCollection` where we give all inputs for the group the same ref, and use that to extract? But I guess that isn't supported currently?

Either way, we should test and document the supported approach :)

2022-04-25 15:19 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +      const validForm: PropTypeInfo = {
Not really, that's a different case.

However, I realise my suggestion doesn't really test our form code at all, but rather the output of the internal util function, and shouldn't even happen. Changes are needed in our test case anyway, see other comment thread.

2022-04-25 15:20 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
Ah nvm, I misread `propInfo.type.name` as `propInfo.source.name` :D

2022-04-26 14:34 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
jummm 🤔, you're right, I was completely forgetting that, I think there's a way simpler solution, as the source name is always defined the validations I added for checking for falsiness are useless, I'll remove them, then our possible conditions become (pasted from prev comment):

Only when the target is a form element: 

- ~~The type is Object but a name was given~~
- ~~The type is Object but no name was given~~
- The type is Object: return FormData
- The type is NOT Object ~~and a name was given~~:
  - If the type is Array return FormData.getAll(), useful for multiple inputs with the same name like checkboxes
  - If the type is NOT Array return FormData.getAll()[0] converted with convertSourceValue
  - If the passed name does not match any child input return undefined
- Anything else: return undefined 

That way we don't need to mess with the utils nor the types, and still don't need the formData boolean

2022-04-26 14:38 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
btw i just pushed that change, not much changed, just the falsiness check and one test

2022-04-26 21:58 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +            if (propInfo.type !== Object && !propInfo.source.name && propInfo.source.formData) {
@ThaNarie I just pushed a few things:

- Refactored tests
- test utilities for this feature, I'm setting the source name as PropTypeInfo.source.name || PropTypeInfo.name, just like the util function in [muban/src/lib/props/getComponentProps.ts](https://github.com/mubanjs/muban/blob/80eec3f845b2d01383cbac28885640a1144ff7d4/src/lib/props/getComponentProps.ts#L55)
- updated docs
- I added the formData boolean again for full FormData extraction

I think every possibility is tested, if there's one missing please let me know, now with the util function new form tests are really easy to create

2022-05-04 21:28 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.testutils.ts
> +  type: typeof Number | typeof String | typeof Boolean | typeof Date | typeof Array | typeof Object,
Fixed

2022-05-04 21:28 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.testutils.ts
> +  type: typeof Number | typeof String | typeof Boolean | typeof Date | typeof Array | typeof Object,
Duplicated comment, resolving it

2022-05-04 21:29 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          const childInputValues = formData.getAll(propInfo.source.name || '');
Duplicated comment, closing it

2022-05-04 21:31 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          const childInputValues = formData.getAll(propInfo.source.name || '');
fixed

2022-05-04 21:36 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (propInfo.type === Object && propInfo.source.name) {
1. I removed that check and added this one instead:
```javascript
if (propInfo.type !== Object && propInfo.source.formData) { // log warning and return undefined }
```
Also added a new test specifically for that case

2. That's exactly how it's working, the only difference is that I'm checking for ```FormData.getAll('name').length``` instead of ```FormData.has(key)```

2022-05-04 21:38 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +      it('Should return FormData object when using type "Object" and formData: true', () => {
Fixed, pleas take a look at https://github.com/mubanjs/muban/pull/75#discussion_r865405580

2022-05-04 21:38 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (propInfo.type === Object && propInfo.source.name) {
Duplicated comment, closing it

2022-05-04 21:38 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +      it('Should return FormData object when using type "Object" and formData: true', () => {
Duplicated comment. closing it

2022-05-04 21:38 UTC, jspolancor commented on docs/api/props.md
> +    ),
Fixed

2022-05-04 21:39 UTC, jspolancor commented on docs/api/props.md
> +    ),
Duplicated comment, closing it

2022-05-04 21:39 UTC, jspolancor commented on docs/guide/props.md
> +* The `form` source allow you to extract _Input state_ from form elements, when targeting an input it will extract the value, when targeting a form it will extract the FormData Object. It allows for
Duplicated comment, closing it

2022-05-04 21:50 UTC, jspolancor commented on docs/guide/props.md
> +* The `form` source allow you to extract _Input state_ from form elements, when targeting an input it will extract the value, when targeting a form it will extract the FormData Object. It allows for
Agree, lots to explain

2022-05-04 22:59 UTC, ThaNarie requested changes

2022-05-04 22:59 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (propInfo.type !== Object && propInfo.source.formData) {
This bit can be simplified, since we're doing duplicate checks in different places now.

```ts
const formData = new FormData(element as HTMLFormElement);

if (propInfo.source.formData) {
  if (propInfo.type !== Object) {
    console.warn(....);
    return undefined;
  }
  
  return formData;
}

// do existing things with single field
```

2022-05-04 22:59 UTC, ThaNarie commented on docs/guide/props.md
> +* The `form` source allow you to extract _Input state_ from form elements, when targeting an input it will extract the value, when targeting a form it will extract the FormData Object. It allows for
Not seeing a ticket for it yet though?

2022-05-05 16:15 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (propInfo.type !== Object && propInfo.source.formData) {
Fixed

2022-05-05 16:24 UTC, jspolancor commented on docs/guide/props.md
> +* The `form` source allow you to extract _Input state_ from form elements, when targeting an input it will extract the value, when targeting a form it will extract the FormData Object. It allows for
Here it is https://github.com/mubanjs/muban/issues/81

2022-05-18 15:08 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.testutils.ts
> +function getMixedPropTypeInfo(
I just added a generic function and implemented it on the tests for this feature

2022-05-24 14:43 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.test.ts
> +      const radioFormDataValue = getFullPropTypeInfo('onBoolean', form, 'maritalStatus');
Actually it is testing for the radio button directly

In line 183

```typescript
expect(createFormPropertySource()(form).getProp(radioDirectValue.string.asInput)).toBe(
    'married',
);
```

The `.asInput` uses the input as target, and `.asForm` uses the parent form as target, like the next test in line 192:

```typescript
it('Should return the selected radio value when using the parent form as a target', () => {
    expect(createFormPropertySource()(form).getProp(radioFormDataValue.string.asForm)).toBe(
        'single',
    );
});
```

PS: how do you link to a line of code in a github comment? I always paste the whole line/s 🤔

2022-05-24 14:44 UTC, jspolancor commented on CHANGELOG.md
> +## Unreleased - feature/input-prop-type-source
Fixed

2022-05-24 14:48 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (isRadio && !isForm) {
You're absolutely right! fixed

2022-05-27 13:26 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (propInfo.type === Array && !valueIsStringifiedArray) return childInputValues;
Can't this be done inside the `if (childInputValues.length > 0 && propInfo.type === Array)` ?

2022-05-27 13:26 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (childInputValues.length === 0) return previousValue;
In the previous version of the code, this check would return `undefined`, why the change?
If this was not intentional, do we have a missing test case?

2022-05-27 13:26 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (childInputValues.length > 0 && propInfo.type === Array) {
It seems the `if (propInfo.type === Object) return previousValue` behaviour is now gone?
Instead, it could end up in the `convertSourceValue`

Maybe also a missing test case?

2022-05-31 15:41 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (propInfo.type === Array && !valueIsStringifiedArray) return childInputValues;
Yes, fixed

2022-05-31 15:41 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (childInputValues.length === 0) return previousValue;
My bad, it should be undefined, fixed!

2022-05-31 15:44 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (childInputValues.length > 0 && propInfo.type === Array) {
This was intentional, that line was breaking the case of a stringified object as an input value
```html
<input type="text" value='{ "zip": "110010"}'/>
```
now it will convert the value to a valid object with `convertSourceValue()`

2022-05-31 19:00 UTC, ThaNarie commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (childInputValues.length === 0) return previousValue;
What about the 2nd thing:

> If this was not intentional, do we have a missing test case?

2022-05-31 20:20 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (childInputValues.length === 0) return previousValue;
I think we're good with:
https://github.com/mubanjs/muban/blob/f8dc07b4edc279aedc74c3ab9d59bcf68e800a67/src/lib/props/property-sources/createFormPropertySource.test.ts#L245-L252

2022-09-20 14:27 UTC, ThaNarie commented on CHANGELOG.md
> +- Add `form` source
```suggestion
- Add `form` source, allowing you to easily extract initial values from forms or inputs
```

2022-09-21 16:49 UTC, jspolancor commented on src/lib/props/property-sources/createFormPropertySource.ts
> +          if (childInputValues.length === 0) return previousValue;
Now I remember, `previousValue` is a variable that's changed using [this pipe](https://github.com/mubanjs/muban/blob/f8dc07b4edc279aedc74c3ab9d59bcf68e800a67/src/lib/props/property-sources/createFormPropertySource.ts#L102-L105), the `formDataValue` function is the first one to be called, and the one being tested [here](https://github.com/mubanjs/muban/blob/f8dc07b4edc279aedc74c3ab9d59bcf68e800a67/src/lib/props/property-sources/createFormPropertySource.test.ts#L245-L252), the value is undefined by default, that's why the test did not fail, in that first call `previousValue` is in fact undefined

2022-09-26 15:44 UTC, ThaNarie approved these changes

2022-09-26 15:51 UTC, merged