Add 'event' binding to componentCollection in applybindings.ts
mubanjs/muban pull request #82
Opened 2022-05-31 21:11 UTC by jspolancor

- Add 'event' binding to componentCollection in applybindings.ts
- Add tests for the feature

2022-06-01 07:53 UTC, ThaNarie requested changes
Implementation itself looks good 👍

2022-06-01 07:53 UTC, ThaNarie commented on src/lib/bindings/applyBindings.test.ts
> +        button: refElement('button'),
The test is saying `should apply event bindings to a component`. but it's testing a `refElement`. You should instead be testing `refComponent`.

2022-06-01 07:53 UTC, ThaNarie commented on src/lib/bindings/applyBindings.test.ts
> +    document.body.appendChild(element);
Wouldn't it be easier to just set the `innerHTML` to a html string instead?

2022-06-02 16:42 UTC, jspolancor commented on src/lib/bindings/applyBindings.test.ts
> +        button: refElement('button'),
😄 Fixed!

2022-09-20 14:24 UTC, ThaNarie approved these changes

2022-09-20 18:08 UTC, merged