Chore/play function for all stories
mubanjs/muban pull request #94
Opened 2023-01-10 14:49 UTC by jspolancor

Adds .play function to all stories

2023-01-16 09:45 UTC, ThaNarie requested changes
Besides the PR feedback, i would also see if we're asserting the right things (in all situations).

Most stories output something to the DOM in an "info" container, so they are visible to the user, and I believe most of your tests check that output.

However, tests are more correct, and have probably more helpful error messages if you directly test against the DOM of the actual elements where that is applicable.

2023-01-16 09:45 UTC, ThaNarie commented on test-storybook/src/utils/timers.ts
> +  expect(element[property]).toBe(expectedValue);
Wouldn't use `waitFor` be better, then you don't have to wait an explicit value, but it will pass as soon as it matches the expectation within the given timout.

https://testing-library.com/docs/dom-testing-library/api-async/#waitfor

I would probably not even use these utils, as they "force" you to use the default `toBe`, which isn't really useful if you check for certain things in the DOM.

`jest-dom` (https://github.com/testing-library/jest-dom) has a bunch of specific matchers to use instead of `toBe` which:
1. immediately check a state in the DOM, so you won't have to extract it yourself
2. give way more descriptive error messages

2023-01-23 20:36 UTC, jspolancor commented on test-storybook/src/utils/timers.ts
> +  expect(element[property]).toBe(expectedValue);
I use the "info" container to test against internal values inside the components, like private refs, for example in the Checked stories I'm comparing private refs with DOM values to see if they match. Here some private refs are used as binding values for the `checked` binding and then the refs values are the data printed to the "info" container:
https://github.com/mubanjs/muban/blob/4557161ce0231d1e88de79b815a7a9b541bf4aea/test-storybook/src/components/bindings/checked/Checked.stories.ts#L24-L44
Then I test if those internal values match the DOM values
https://github.com/mubanjs/muban/blob/4557161ce0231d1e88de79b815a7a9b541bf4aea/test-storybook/src/components/bindings/checked/Checked.stories.ts#L59-L69
It was the best solution I found to not only test if the DOM was updated correctly but to also test if the internal data inside the component is updated accordingly. I'm double checking every story to see if I overdid this pattern (Maybe I did 😄) and remove it when it's not necessary, I'm also checking where I could implement the jest-dom utils instead of .toBe

Now for the 'waitFor' util I created, I didn't know there was a preinstalled utility for that, I'll remove my util in favour of the testing-library one

2023-01-25 16:45 UTC, jspolancor commented on test-storybook/src/utils/timers.ts
> +  expect(element[property]).toBe(expectedValue);
@ThaNarie the `wait` and `waitToBe` utils were removed in favour of `waitFor`, matchers were updated, the info container is only used when testing prop extraction

2023-02-01 16:27 UTC, merged