Update Component to avoid double mounting of ref components
mubanjs/muban pull request #99
Opened 2023-03-13 23:16 UTC by jspolancor

@ThaNarie this is my initial approach to prevent double mounting

I have three variables: `newInstance` is a fresh instance created with the given createOptions, and `instance` that can be a previously existing instance or a reference to `newInstance` and `isInstantiated` a boolean that's `true` if there's a previous instance created

Then I spread refs, props and reactivePros from `instance` when setting those values for `newInstance`, that way I'm using the `newInstance` as an extended previous instance

Then I'm passing `instance` to `setupComponent()` and a new argument `alreadyInstantiated` to conditionally trigger `mount()`

That way bindings are applied only In one instance, makes sense?

2023-03-15 14:26 UTC, ThaNarie commented
It looks like this PR doesn't do what the title says. Instead of preventing double mounting, it allows double mounting and tries to make it work with multiple bindings.

I've gone trough the code again, and found this snippet:
https://github.com/mubanjs/muban/blob/69195af95703a152587355c95d8625642fcdfd15/src/lib/refs/refDefinitions.ts#L82-L90

I believe you still get this error log in your branch, right?
I've been thinking how we would solve this, and it's quite tricky.
- there are cases where a grandparent should "own" a deeply nested component, for example when the HTML is dynamically inserted (e.g. in a tab component, or accordion), but in that scenario that would be the ONLY owner.
- i can't think of any valid cases where we want multiple owners of a component/ref to apply bindings. This is something you can't do in other frameworks either. And if needed, you can still use querySelector in the setup function to do some custom things.
- if we would allow for multiple owners, we need to make sure the direct parent would be the actual parent, which might be hard based on execution order and other things.

So i feel we should probably disallow multiple owners of a single ref, and throw hard errors.
For refComponents, that would be in the above snippet.
For refElements, we don't have anything in place, so we would need to add a similar construct to `globalInstance.instances`, but then for element refs.

2023-04-05 13:49 UTC, ThaNarie requested changes

2023-04-05 13:49 UTC, ThaNarie commented on src/lib/refs/refDefinitions.ts
> +    );
Maybe we should also include some useful information about the `ref` in here? :)

2023-04-05 13:49 UTC, ThaNarie commented on src/lib/refs/refDefinitions.test.ts
> +  describe('when having multiple owners of a ref', () => {
This name is copied from above

2023-04-05 13:49 UTC, ThaNarie commented on src/lib/refs/refDefinitions.test.ts
> +  describe('when having multiple owners of a ref', () => {
We should also have a test for a component collection.

2023-04-27 21:30 UTC, jspolancor commented on src/lib/refs/refDefinitions.ts
> +    );
Done, just added the element to the error

2023-04-27 21:30 UTC, jspolancor commented on src/lib/refs/refDefinitions.test.ts
> +  describe('when having multiple owners of a ref', () => {
Fixed

2023-04-27 21:30 UTC, jspolancor commented on src/lib/refs/refDefinitions.test.ts
> +  describe('when having multiple owners of a ref', () => {
Done!

2023-05-01 08:25 UTC, ThaNarie requested changes
Last small change, looks good otherwise :)

2023-05-01 08:25 UTC, ThaNarie commented on src/lib/refs/refDefinitions.ts
> +        `This refComponent does already exist as part of another parent
Can we also include the `${element}` here, as you did with the other one.

2023-05-15 19:35 UTC, jspolancor commented on src/lib/refs/refDefinitions.ts
> +        `This refComponent does already exist as part of another parent
Done!

2023-05-23 17:04 UTC, ThaNarie commented on src/lib/refs/refDefinitions.ts
> +        ${existingComponent.__instance.parent}`,
The objects `element` and `existingComponent.__instance.parent` are inlined in the error string, so have limited information.

In node it would show this:
```
This refComponent [object HTMLDivElement] does already exist as part of another parent
            [object Object]
```

In React they would often log an "error" with lots of useful information, and then throw the error.
If we log it, we could have those inlined items logged separately, so you can inspect the objects, so it's more useful.

How do you feel about this?

2023-05-29 16:23 UTC, jspolancor commented on src/lib/refs/refDefinitions.ts
> +        ${existingComponent.__instance.parent}`,
I don't think a developer would need much data to solve this error, we only need to know two things, the refs html element and the parent name, to log the html element in node we could use the outerHTML property, and for the existing parent we could use the name, changing those two things will result in this log:
![image](https://github.com/mubanjs/muban/assets/5639960/56682bbc-297c-4ac9-b547-f212c584fe8d)
I like the idea of having logs with more information about the components but for this specific error I don't think more data is needed, what do you think?

2023-05-30 10:40 UTC, ThaNarie commented on src/lib/refs/refDefinitions.ts
> +        ${existingComponent.__instance.parent}`,
I wasn't sure how it would output in the browser (if it's different from node or not).

I'm fine with improving (stringifying) the current error with your suggestions in this case.

2023-06-08 14:56 UTC, jspolancor commented on src/lib/refs/refDefinitions.ts
> +        ${existingComponent.__instance.parent}`,
Fixed

2023-06-12 07:55 UTC, merged